// <auto-generated />
namespace PassionProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class migration31 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration31));
        
        string IMigrationMetadata.Id
        {
            get { return "202002171948063_migration31"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
